### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dvabuzyarov** [dvabuzyarov/moq.ts#449]
RangeError: Maximum call stack size exceeded
	    at <Jasmine>
	    at HTMLDivElement.Object.toString (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:1556:1)
	    at ConstantFormatter.format (http://localhost:9876/_karma_webpack_/node_modules/moq.ts/fesm2015/moq.ts.js:1901:1)
	    at ConstantFormatter.format (http://localhost:9876/_karma_webpack_/node_modules/moq.ts/fesm2015/moq.ts.js:1897:1)
	    at ConstantFormatter.format (http://localhost:9876/_karma_webpack_/node_modules/moq.ts/fesm2015/moq.ts.js:1897:1)
	    at ConstantFormatter.format (http://localhost:9876/_karma_webpack_/node_modules/moq.ts/fesm2015/moq.ts.js:1897:1)
	    at ConstantFormatter.format (http://localhost:9876/_karma_webpack_/node_modules/moq.ts/fesm2015/moq.ts.js:1897:1)
	    at ConstantFormatter.format (http://localhost:9876/_karma_webpack_/node_modules/moq.ts/fesm2015/moq.ts.js:1897:1)
	    at ConstantFormatter.format (http://localhost:9876/_karma_webpack_/node_modules/moq.ts/fesm2015/moq.ts.js:1897:1)
	    at ConstantFormatter.format (http://localhost:9876/_karma_webpack_/node_modules/moq.ts/fesm2015/moq.ts.js:1897:1)
	    at ConstantFormatter.format (http://localhost:9876/_karma_webpack_/node_modules/moq.ts/fesm2015/moq.ts.js:1897:1)

```typescript
class ConstantFormatter {
    format(object) {
        if (object instanceof It)
            return `It.Is(${object.predicate})`;
        if (object instanceof String || typeof object === "string")
            return `\'${object}\'`;
        if (object instanceof Array) {
            const description = [];
            for (const index of Object.keys(object)) {
// problem could be here for a big objects tree
                description.push(new ConstantFormatter().format(object[index]));
            }
            return `[${description}]`;
        }
        return `${object}`;
    }
}
```

**Comment by dvabuzyarov** [comment]
This bug does not have a general solution. The root cause is assigning to a mocked property a big object that leads to the execution in stringifying. As workaround it could be patched with a custom implementation of formatters.

``` typescript
export class CustomSetPropertyFormatter {

  constructor(
    private constantFormatter: ConstantFormatter,
    private propertyKeyFormatter: PropertyKeyFormatter) {

  }

  public format(expression: SetPropertyInteraction): string {
    const propertyKey = this.propertyKeyFormatter.format(expression.name);
    // patch for the exception
    if (expression.name === '__ngContext__') {
      return `Assignment of ${expression.value} to property \'${propertyKey}\'`;
    }

    const value = this.constantFormatter.format(expression.value);
    return `Assignment of ${value} to property \'${propertyKey}\'`;
  }
}

Mock.options = {
  injectorConfig: new EqualMatchingInjectorConfig([], [
    {provide: SetPropertyFormatter, useClass: CustomSetPropertyFormatter, deps: [ConstantFormatter, PropertyKeyFormatter]},
  ])
};
```
